State.create(:name => "ALASKA", :abbr => "AK", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 1)    
State.create(:name => "ALABAMA", :abbr => "AL", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 2)    
State.create(:name => "ARKANSAS", :abbr => "AR", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 3)    
State.create(:name => "AMERICAN SAMOA", :abbr => "AS", :country => "UNITED STATES OF AMERICA", :type => "TERRITORY", :id => 4)    
State.create(:name => "ARIZONA", :abbr => "AZ", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 5)    
State.create(:name => "CALIFORNIA", :abbr => "CA", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 6)    
State.create(:name => "COLORADO", :abbr => "CO", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 7)    
State.create(:name => "CONNECTICUT", :abbr => "CT", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 8)    
State.create(:name => "DISTRICT OF COLUMBIA", :abbr => "DC", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 9)    
State.create(:name => "DELAWARE", :abbr => "DE", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 10)    
State.create(:name => "FLORIDA", :abbr => "FL", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 11)    
State.create(:name => "GEORGIA", :abbr => "GA", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 12)    
State.create(:name => "GUAM", :abbr => "GU", :country => "UNITED STATES OF AMERICA", :type => "TERRITORY", :id => 13)    
State.create(:name => "HAWAII", :abbr => "HI", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 14)    
State.create(:name => "IOWA", :abbr => "IA", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 15)    
State.create(:name => "IDAHO", :abbr => "ID", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 16)    
State.create(:name => "ILLINOIS", :abbr => "IL", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 17)    
State.create(:name => "INDIANA", :abbr => "IN", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 18)    
State.create(:name => "KANSAS", :abbr => "KS", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 19)    
State.create(:name => "KENTUCKY", :abbr => "KY", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 20)    
State.create(:name => "LOUISIANA", :abbr => "LA", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 21)    
State.create(:name => "MASSACHUSETTS", :abbr => "MA", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 22)    
State.create(:name => "MARYLAND", :abbr => "MD", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 23)    
State.create(:name => "MAINE", :abbr => "ME", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 24)    
State.create(:name => "MICHIGAN", :abbr => "MI", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 25)    
State.create(:name => "MINNESOTA", :abbr => "MN", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 26)    
State.create(:name => "MISSOURI", :abbr => "MO", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 27)    
State.create(:name => "MARIANA ISLANDS", :abbr => "MP", :country => "UNITED STATES OF AMERICA", :type => "TERRITORY", :id => 28)    
State.create(:name => "MISSISSIPPI", :abbr => "MS", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 29)    
State.create(:name => "MONTANA", :abbr => "MT", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 30)    
State.create(:name => "NORTH CAROLINA", :abbr => "NC", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 31)    
State.create(:name => "NORTH DAKOTA", :abbr => "ND", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 32)    
State.create(:name => "NEBRASKA", :abbr => "NE", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 33)    
State.create(:name => "NEW HAMPSHIRE", :abbr => "NH", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 34)    
State.create(:name => "NEW JERSEY", :abbr => "NJ", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 35)    
State.create(:name => "NEW MEXICO", :abbr => "NM", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 36)    
State.create(:name => "NEVADA", :abbr => "NV", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 37)    
State.create(:name => "NEW YORK", :abbr => "NY", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 38)    
State.create(:name => "OHIO", :abbr => "OH", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 39)    
State.create(:name => "OKLAHOMA", :abbr => "OK", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 40)    
State.create(:name => "OREGON", :abbr => "OR", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 41)    
State.create(:name => "PENNSYLVANIA", :abbr => "PA", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 42)    
State.create(:name => "PUERTO RICO", :abbr => "PR", :country => "UNITED STATES OF AMERICA", :type => "TERRITORY", :id => 43)    
State.create(:name => "RHODE ISLAND", :abbr => "RI", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 44)    
State.create(:name => "SOUTH CAROLINA", :abbr => "SC", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 45)    
State.create(:name => "SOUTH DAKOTA", :abbr => "SD", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 46)    
State.create(:name => "TENNESSEE", :abbr => "TN", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 47)    
State.create(:name => "TEXAS", :abbr => "TX", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 48)    
State.create(:name => "UTAH", :abbr => "UT", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 49)    
State.create(:name => "VIRGINIA", :abbr => "VA", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 50)    
State.create(:name => "VIRGIN ISLANDS", :abbr => "VI", :country => "UNITED STATES OF AMERICA", :type => "TERRITORY", :id => 51)    
State.create(:name => "VERMONT", :abbr => "VT", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 52)    
State.create(:name => "WASHINGTON", :abbr => "WA", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 53)    
State.create(:name => "WISCONSIN", :abbr => "WI", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 54)    
State.create(:name => "WEST VIRGINIA", :abbr => "WV", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 55)    
State.create(:name => "WYOMING", :abbr => "WY", :country => "UNITED STATES OF AMERICA", :type => "STATE", :id => 56)    
State.create(:name => "ONTARIO", :abbr => "ON", :country => "CANADA", :type => "PROVINCE", :id => 57)    
State.create(:name => "QUEBEC", :abbr => "QC", :country => "CANADA", :type => "PROVINCE", :id => 58)    
State.create(:name => "NOVA SCOTIA", :abbr => "NS", :country => "CANADA", :type => "PROVINCE", :id => 59)    
State.create(:name => "NEW BRUNSWICK", :abbr => "NB", :country => "CANADA", :type => "PROVINCE", :id => 60)    
State.create(:name => "MANITOBA", :abbr => "MB", :country => "CANADA", :type => "PROVINCE", :id => 61)    
State.create(:name => "BRITISH COLUMBIA", :abbr => "BC", :country => "CANADA", :type => "PROVINCE", :id => 62)    
State.create(:name => "PRINCE EDWARD ISLAND", :abbr => "PE", :country => "CANADA", :type => "PROVINCE", :id => 63)    
State.create(:name => "SASKATCHEWAN", :abbr => "SK", :country => "CANADA", :type => "PROVINCE", :id => 64)    
State.create(:name => "ALBERTA", :abbr => "AB", :country => "CANADA", :type => "PROVINCE", :id => 65)    
State.create(:name => "NEWFOUNDLAND AND LABRADOR", :abbr => "NL", :country => "CANADA", :type => "PROVINCE", :id => 66)    
State.create(:name => "NORTHWEST TERRITORIES", :abbr => "NT", :country => "CANADA", :type => "TERRITORY", :id => 67)    
State.create(:name => "YUKON", :abbr => "YT", :country => "CANADA", :type => "TERRITORY", :id => 68)    
State.create(:name => "NUNAVUT", :abbr => "NU", :country => "CANADA", :type => "TERRITORY", :id => 69)    
